# Generated by Django 4.2.7 on 2023-12-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0002_advisor_alter_club_advisor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubuser",
            name="club",
            field=models.ManyToManyField(null=True, to="hub.club"),
        ),
        migrations.AlterField(
            model_name="hubuser",
            name="department",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hubuser",
            name="gender",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
