# Generated by Django 4.2.7 on 2023-12-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0003_alter_hubuser_club_alter_hubuser_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubuser",
            name="club",
            field=models.ManyToManyField(blank=True, to="hub.club"),
        ),
    ]
